### ISSUE TITLE
Token Usage in model

### ISSUE THREAD

**Issue by icorson3** [lao9/api_curious_github_loliveri#2]
@lao9 all the api calls you are making in the user model/thru service can be without the token. This is an open api call so no token needed to this info.

**Comment by lao9** [comment]
hey @icorson3 - i'm not sure i'm following, I just tried to make those same requests in postman and it doesn't work without the token. I'm assuming you're referring to this model?: https://github.com/lao9/api_curious_github_loliveri/blob/master/app/models/user.rb
